<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYLtwpga\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYLtwpga/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYLtwpga.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYLtwpga\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYLtwpga\App_KernelDevDebugContainer([
    'container.build_hash' => 'YLtwpga',
    'container.build_id' => '94f5eaf1',
    'container.build_time' => 1645384564,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYLtwpga');
